# Generated by Django 5.2.11 on 2026-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('pest_or_disease', models.CharField(max_length=22)),
                ('pest_type', models.CharField(blank=True, max_length=22)),
                ('description', models.TextField()),
                ('what_to_look_for', models.TextField(blank=True)),
                ('how_it_is_treated', models.TextField(blank=True)),
                ('how_to_prevent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active/Published'), ('REMOVAL_REQUESTED', 'Removal Requested')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
