# Generated by Django 5.2.11 on 2026-02-22 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='pest_or_disease',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='pest_type',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pest',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to an image online', max_length=500),
        ),
        migrations.AddField(
            model_name='pest',
            name='removal_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion request'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='plantpests.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='pest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pests', to='plantpests.category'),
        ),
    ]
