# Generated by Django 5.2.11 on 2026-02-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpests', '0002_remove_pest_pest_or_disease_remove_pest_pest_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pest',
            options={'verbose_name': 'Pest or Disease', 'verbose_name_plural': 'Pests and Diseases'},
        ),
        migrations.AlterField(
            model_name='pest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active/Published'), ('REMOVAL REQUESTED', 'Removal Requested')], default='PENDING', max_length=20),
        ),
    ]
