# Generated by Django 5.2.11 on 2026-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpests', '0003_alter_pest_options_alter_pest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active/Published'), ('REMOVAL_REQUESTED', 'Removal Requested')], default='PENDING', max_length=20),
        ),
    ]
